name: Composite Action Example
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write Badge
        uses: ./.github/actions/example-composite-action
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
