name: Javascript Action Example
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Write Badge
        uses: ./.github/actions/example-js-action
        with:
          file-name: js-example.svg
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          badge-branch: badges
