name: PHP Workflow Example
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - run: source <(php php_example.php)
      - name: Write badge
        uses: action-badges/core@0.3.0
        with:
          file-name: php-example.svg
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          badge-branch: badges
          label: "${{ env.LABEL }}"
          message: "${{ env.MESSAGE }}"
          message-color: "${{ env.MESSAGE-COLOR }}"
