name: Python Workflow Example
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: source <(python python_example.py)
      - name: Write badge
        uses: action-badges/core@0.2.1
        with:
          file-name: python-example.svg
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          badge-branch: badges
          label: "${{ env.LABEL }}"
          message: "${{ env.MESSAGE }}"
          message-color: "${{ env.MESSAGE-COLOR }}"
