name: Yaml Workflow Example
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Write Badge
        uses: action-badges/core@0.4.0
        with:
          file-name: yaml-example.svg
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          badge-branch: badges
          label: example
          message: yaml
          message-color: blue
